sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  # --ignore-platform-reqs, because https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/2722
  - composer update -n --prefer-dist --ignore-platform-reqs

script:
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
